user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

