# Route gerant la homepage:
front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

# Routes gerant l'onglet static:
front_office_static_cgu:
    path:     /ConditionsGeneralesUtilisation
    defaults: { _controller: FrontOfficeBundle:Static:conditions}

front_office_static_mentions:
    path:     /MentionsLegales
    defaults: { _controller: FrontOfficeBundle:Static:mentions}

front_office_static_contact:
    path:     /contact 
    defaults: { _controller: FrontOfficeBundle:Static:contact}

# Routes gerant les invitations:
front_office_invitation_new:
    path:     /newInvitation/{userTo, teamTo, TeamFrom}
    defaults: { _controller: FrontOfficeBundle:Invitation:new, userTo: null, teamTo: null, teamFrom: null}

    # Acceptation d'une invitation:
front_office_invitation_response:
    path:     /response/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:response}
    requirements: 
        id: "[0-9]+"

    # Refus d'une invitation: 
front_office_invitation_denied:
    path:     /deniedInvitation/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:denied}
    requirements: 
        id: "[0-9]+"

    # Suppression d'une invitation de son profil personnel:
front_office_invitation_deletefrom_monprofil:
    path:     /deleteInvitationFromMonProfil/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:deleteFromMonProfil}

front_office_invitation_delete:
    path:     /deleteInvitation/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:delete}

# Routes administrant le blog:
front_office_blog_homepage:
    path:     /blogHomepage 
    defaults: { _controller: FrontOfficeBundle:Blog:homepage}

    # Tri des Articles par category:
front_office_blog_triBySport:
    path:     /triByCategories/{sport}
    defaults: { _controller: FrontOfficeBundle:Blog:triBySport}

    # Vue d'un article en détail:
front_office_blog_one:
    path:     /One/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:one}
    requirements: 
        id: "[0-9]+"

# Routes gerant les users:
    # Route Mon Profil:
front_office_user_update:
    path:     /update
    defaults: { _controller: FrontOfficeBundle:User:update}

    # Liste des derniers inscrits:
front_office_users_list:
    path:     /listUsers
    defaults: { _controller: FrontOfficeBundle:User:list}

    # Voir la fiche d'un user:
front_office_user_one:
    path:     /oneUser/{id}
    defaults: { _controller: FrontOfficeBundle:User:one}
    requirements: 
        id: "[0-9]+"

    # Ajouter un user à sa liste d'amis:
front_office_user_getFriend:
    path:     /getFriend/{id}
    defaults: { _controller: FrontOfficeBundle:User:getFriend}
    requirements: 
        id: "[0-9]+"

    # Voir sa liste d'amis:
front_office_user_showFriends:
    path:     /showFriends 
    defaults: { _controller: FrontOfficeBundle:User:showFriends}

    # Voir les équipes dont il est membre:
front_office_user_showTeams:
    path:      /showTeams
    defaults: { _controller: FrontOfficeBundle:User:showTeams}

    # Voir ses invitations envoyées et reçues:
front_office_user_invitations:
    path:     /showInvitations
    defaults: { _controller: FrontOfficeBundle:User:showInvitations}

# Routes gerant les Teams:
front_office_team_list:
    path:     /listTeams
    defaults: { _controller: FrontOfficeBundle:Team:listTeams}

    # Voir une team en détail:
front_office_team_one:
    path:     /oneTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:oneTeam}
    requirements: 
        id: "[0-9]+"

    # Créer une nouvelle team:
front_office_team_new:
    path:     /newTeam
    defaults: { _controller: FrontOfficeBundle:Team:new}

    # Ajout d'un user à une team:
front_office_team_addUser:
    path:     /addUser/{id}
    defaults: { _controller: FrontOfficeBundle:Team:addUser}
    requirements: 
        id: "[0-9]+"

    # Suppression d'un user d'une team:
front_office_team_user_delete:
    path:     /userDelete/{idUser,idTeam}
    defaults: { _controller: FrontOfficeBundle:Team:userDelete}

    # Suppression d'une team complète:
front_office_team_delete:
    path:     /deleteTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:teamDelete}
    requirements: 
        id: "[0-9]+"