# Route gerant la homepage:
front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

# Routes gerant l'onglet static:
front_office_static_cgu:
    path:     /ConditionsGeneralesUtilisation
    defaults: { _controller: FrontOfficeBundle:Static:conditions}

front_office_static_mentions:
    path:     /MentionsLegales
    defaults: { _controller: FrontOfficeBundle:Static:mentions}

front_office_static_contact:
    path:     /contact
    defaults: { _controller: FrontOfficeBundle:Static:contact}

# Routes gerant les invitations:
front_office_invitation_new:
    path:     /newInvitation/{userTo, teamTo, TeamFrom}
    defaults: { _controller: FrontOfficeBundle:Invitation:new, userTo: null, teamTo: null, teamFrom: null}

    # Détail d'une invitation:
front_office_invitation_one:
    path:     /oneInvitation/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:oneInvitation}

    # Acceptation d'une invitation:
front_office_invitation_response:
    path:     /response/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:response}
    requirements: 
        id: "[0-9]+"

    # Refus d'une invitation: 
front_office_invitation_denied:
    path:     /deniedInvitation/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:denied}
    requirements: 
        id: "[0-9]+"

    # Suppression d'une invitation de son profil personnel:
front_office_invitation_deletefrom_monprofil:
    path:     /deleteInvitationFromMonProfil/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:deleteFromMonProfil}

    # Suppression d'une invitation de la liste:
front_office_invitation_delete:
    path:     /deleteInvitation/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:delete}

# Routes administrant le blog:
front_office_blog_homepage:
    path:     /blogHomepage 
    defaults: { _controller: FrontOfficeBundle:Blog:homepage}

#     # Route administrant la sidebar:
# front_office_blog_sidebar_list:
#     path:     /listSport
#     defaults: { _controller: FrontOfficeBundle:Blog:list}

    # Tri des Articles par category:
front_office_blog_triBySport:
    path:     /triByCategories/{sport}
    defaults: { _controller: FrontOfficeBundle:Blog:triBySport}

    # Vue d'un article en détail:
front_office_blog_one:
    path:     /One/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:one}
    requirements: 
        id: "[0-9]+"

# Routes gerant les users:
    # Route Mon Profil:
front_office_user_update:
    path:     /update
    defaults: { _controller: FrontOfficeBundle:User:update}

    # Liste des derniers inscrits:
front_office_users_list:
    path:     /listUsers
    defaults: { _controller: FrontOfficeBundle:User:list}

    # Voir la fiche d'un user:
front_office_user_one:
    path:     /oneUser/{id}
    defaults: { _controller: FrontOfficeBundle:User:one}
    requirements: 
        id: "[0-9]+"

    # Ajouter un user à sa liste d'amis:
front_office_user_getFriend:
    path:     /getFriend/{id}
    defaults: { _controller: FrontOfficeBundle:User:getFriend}
    requirements: 
        id: "[0-9]+"

    # Retirer un user de sa liste d'amis:
front_office_user_getOutFriend:
    path:     /getOutFriend/{id}
    defaults: { _controller: FrontOfficeBundle:User:getOutFriend}

    # Voir ses amis:
front_office_user_showFriends:
    path:     /showFriends 
    defaults: { _controller: FrontOfficeBundle:User:showFriends}

    # Voir ses équipes:
front_office_user_showTeams:
    path:      /showTeams
    defaults: { _controller: FrontOfficeBundle:User:showTeams}

    # Voir ses articles postés:
front_office_user_showArticles:
    path:     /showArticles 
    defaults: { _controller: FrontOfficeBundle:User:showArticles}   

    # Voir ses invitations envoyées et reçues:
front_office_user_invitations:
    path:     /showInvitations
    defaults: { _controller: FrontOfficeBundle:User:showInvitations}

    # Voir ses tournois:
front_office_user_showTournaments:
    path:     /showTournaments/{id_tournament}
    defaults: { _controller: FrontOfficeBundle:User:showTournaments, id_tournament:null}

     # Voir ses matches:
front_office_user_showMatches:
    path:     /showMatches 
    defaults: { _controller: FrontOfficeBundle:User:showMatches}

# Routes gerant les Teams:
front_office_team_list:
    path:     /listTeams
    defaults: { _controller: FrontOfficeBundle:Team:listTeams}

    # Voir une team en détail:
front_office_team_one:
    path:     /oneTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:oneTeam}
    requirements: 
        id: "[0-9]+"

    # Créer une nouvelle team:
front_office_team_new:
    path:     /newTeam
    defaults: { _controller: FrontOfficeBundle:Team:new}

    # Demande d'intégration d'un user dans une team:
front_office_team_userAskingTeam:
    path:     /userAskingTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:userAskingTeam}

    # Ajout d'un user à une team:
# front_office_team_addUser:
#     path:     /addUser/{idTeam}
#     defaults: { _controller: FrontOfficeBundle:Team:addUser}
#     requirements: 
#         id: "[0-9]+"

    # Suppression d'un user d'une team:
front_office_team_user_delete:
    path:     /userDelete/{idUser,idTeam}
    defaults: { _controller: FrontOfficeBundle:Team:userDelete}
    requirements: 
        id: "[0-9]+"

    # Suppression d'une team complète:
front_office_team_delete:
    path:     /deleteTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:teamDelete}
    requirements: 
        id: "[0-9]+"

    # Dissolution d'une equipe par retrait de son createur de son poste d'admin:
front_office_team_dissolveTeam:
    path:     /dissolveTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:dissolveTeam}

    # Tri des teams par Sport:
front_office_team_triBySport:
    path:     /triBySport/{sportPracticed}
    defaults: { _controller: FrontOfficeBundle:Team:triBySport}

    # Tri des teams par Ground et par Sport: 
front_office_team_getTeamsByGroundAndSport:
    path:     /getTeamsByGroundAndSport/{ground,sportPracticed}
    defaults: { _controller: FrontOfficeBundle:Team:getTeamsByGroundAndSport}

# Routes gérant les terrains:
front_office_ground_list:
    path:     /groundList 
    defaults: { _controller: FrontOfficeBundle:Ground:groundList}

    # Vue d'un terrain :
front_office_ground_one:
    path:    /oneGround/{id}
    defaults: { _controller: FrontOfficeBundle:Ground:oneGround}

    # Creation d'un terrain :
front_office_ground_new:
    path:    /newGround 
    defaults: { _controller:FrontOfficeBundle:Ground:newGround}

    # Routes administrant les tournois:
front_office_tournament_new:
    path:     /newTournament
    defaults: { _controller: FrontOfficeBundle:Tournament:newTournament}

front_office_tournament_list:
    path:     /listTournament
    defaults: { _controller: FrontOfficeBundle:Tournament:listTournament}

front_office_tournament_edit:
    path:     /editTournament/{id}
    defaults: { _controller: FrontOfficeBundle:Tournament:editTournament}

front_office_tournament_update:
    path:     /updateTournament/{id}
    defaults: { _controller: FrontOfficeBundle:Tournament:updateTournament}

    # Routes administrant les matches:
front_office_matche_new:
    path:     /newMatche/
    defaults: { _controller: FrontOfficeBundle:Matche:newMatche}

front_office_matche_cancel:
    path:     /cancelMatch/{id}
    defaults: { _controller: FrontOfficeBundle:Matche:cancelMatch}

front_office_matche_myProfilList:
    path:     /myProfilList/{id}
    defaults: { _controller: FrontOfficeBundle:Matche:myProfilList}

front_office_matche_getScore:
    path:     /getScore/{id}
    defaults: { _controller: FrontOfficeBundle:Matche:getScore}