# Route gerant la homepage:
front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

# Routes gerant l'onglet static:
front_office_static_cgu:
    path:     /ConditionsGeneralesUtilisation
    defaults: { _controller: FrontOfficeBundle:Static:conditions}

front_office_static_mentions:
    path:     /MentionsLegales
    defaults: { _controller: FrontOfficeBundle:Static:mentions}

front_office_static_contact:
    path:     /contact 
    defaults: { _controller: FrontOfficeBundle:Static:contact}

# Routes gerant les invitations:
front_office_invitation_new:
    path:     /newInvitation
    defaults: { _controller: FrontOfficeBundle:Invitation:new }

front_office_invitation_response:
    path:     /response/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:response}

# Routes administrant le blog:
front_office_blog_homepage:
    path:     /blogHomepage 
    defaults: { _controller: FrontOfficeBundle:Blog:homepage}

front_office_blog_list:
    path:     /list/
    defaults: { _controller: FrontOfficeBundle:Blog:list}
    requirements:

front_office_blog_triByCategories:
    path:     /triByCategories/{category}
    defaults: { _controller: FrontOfficeBundle:Blog:triByCategories, category: football}
    requirements: 
        category: (football | basket)

front_office_blog_one:
    path:     /One/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:one}

# Routes gerant les users:
    # Route Mon Profil:
front_office_showUser:
    path:     /showUser
    defaults: { _controller: FrontOfficeBundle:User:showUser}

    # Liste des derniers inscrits:
front_office_users_list:
    path:     /listUsers
    defaults: { _controller: FrontOfficeBundle:User:list}

    # Voir la fiche d'un autre user:
front_office_user_one:
    path:     /oneUser/{id}
    defaults: { _controller: FrontOfficeBundle:User:one}

    # Ajouter un user à sa liste d'amis:
front_office_user_getFriend:
    path:     /getFriend/{id}
    defaults: { _controller: FrontOfficeBundle:User:getFriend}

    # Voir sa liste d'amis:
front_office_user_showFriends:
    path:     /showFriends 
    defaults: { _controller: FrontOfficeBundle:User:showFriends}

    # Voir ses invitations envoyées et reçues:
front_office_user_invitations:
    path:     /showInvitations
    defaults: { _controller: FrontOfficeBundle:User:showInvitations}

# Routes gerant les Teams :
front_office_team_show:
    path:     /showTeams
    defaults: { _controller: FrontOfficeBundle:Team:showTeams}

front_office_team_one:
    path:     /oneTeam/{id}
    defaults: { _controller: FrontOfficeBundle:Team:oneTeam}