# Route gerant la homepage:
front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

# Routes gerant l'onglet static:
front_office_static_cgu:
    path:     /ConditionsGeneralesUtilisation
    defaults: { _controller: FrontOfficeBundle:Static:conditions}

front_office_static_mentions:
    path:     /MentionsLegales
    defaults: { _controller: FrontOfficeBundle:Static:mentions}

# Routes gerant les invitations:
front_office_invitation_new:
    path:     /newInvitation
    defaults: { _controller: FrontOfficeBundle:Invitation:new }

front_office_invitation_response:
    path:     /response/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:response}

# Routes administrant le blog:
front_office_blog_homepage:
    path:     /blogHomepage 
    defaults: { _controller: FrontOfficeBundle:Blog:homepage}

front_office_blog_list:
    path:     /list/
    defaults: { _controller: FrontOfficeBundle:Blog:list}
    requirements:

front_office_blog_triByCategories:
    path:     /triByCategories/{category}
    defaults: { _controller: FrontOfficeBundle:Blog:triByCategories, category: football}
    requirements: 
        category: (football | basket)

front_office_blog_one:
    path:     /One/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:one}

# Route gerant les users:
front_office_showUser:
    path:     /showUser
    defaults: { _controller: FrontOfficeBundle:User:showUser}

front_office_users_list:
    path:     /listUsers
    defaults: { _controller: FrontOfficeBundle:User:list}