front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

# Routes gerant les invitations:
front_office_invitation_new:
    path:     /new 
    defaults: { _controller: FrontOfficeBundle:Invitation:new }

front_office_invitation_response:
    path:     /response/{id}
    defaults: { _controller: FrontOfficeBundle:Invitation:response}

#Routes administrant le blog:
front_office_blog_homepage:
    path:     /blogHomepage 
    defaults: { _controller: FrontOfficeBundle:Blog:homepage}

front_office_blog_list:
    path:     /list/
    defaults: { _controller: FrontOfficeBundle:Blog:list}
    requirements:
        # category: (football | basket)

front_office_blog_one:
    path:     /One/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:one}