# Formulaire d'identification :
fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# Formulaire d'édition de profil :
fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

# Formulaire de création de compte:
fos_user_registration_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

# Formulaire de remise à 0 (perte de password, d'identifiant...):
fos_user_resetting_request:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

# Formulaire de changement de mot de passe:
fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile
