back_office_homepage:
    path:     /homepageBackOffice
    defaults: { _controller: BackOfficeBundle:Homepage:homepage }

# Routes gerant l'administration du blog:
    # Liste des articles:
back_office_article_list:
    path:     /list 
    defaults: { _controller: BackOfficeBundle:Article:list}
    
    # Creation d'un article par l'administrateur:
back_office_article_new:
    path:     /new
    defaults: { _controller: BackOfficeBundle:Article:new}

    # Contrôle des articles par l'administrateur:
back_office_article_admin:
    path:     /adminArticle
    defaults: { _controller: BackOfficeBundle:Article:admin}

    # Validation des articles par l'administrateur:
back_office_article_response:
    path:     /response/{id}
    defaults: { _controller: BackOfficeBundle:Article:response}

    # Mise à jour d'un article par l'administrateur:
back_office_article_update:
    path:     /update/{id}
    defaults: { _controller: BackOfficeBundle:Article:update}

    # Suppression des articles par l'administrateur:
back_office_article_delete:
    path:     /delete/{id}
    defaults: { _controller: BackOfficeBundle:Article:delete}

#  Routes gerant l'administration des commentaires:
    # Contrôle des articles par l'administrateur:
back_office_comment_admin:
    path:     /adminComment
    defaults: { _controller: BackOfficeBundle:Comment:admin}

      # Suppression des comments par l'administrateur:
back_office_comment_delete:
    path:     /delete/{id}
    defaults: { _controller: BackOfficeBundle:Comment:delete}

#  Routes gerant l'administration des terrains de sport :
back_office_ground_list:
    path:     /listGround
    defaults: { _controller: BackOfficeBundle:Ground:list}

back_office_ground_new:
    path:     /newGround
    defaults: { _controller: BackOfficeBundle:Ground:new}

back_office_ground_update:
    path:     /updateGround/{id}
    defaults: { _controller: BackOfficeBundle:Ground:update}

back_office_ground_delete:
    path:     /deleteGround/{id}
    defaults: { _controller: BackOfficeBundle:Ground:delete}

# Routes gerant les users:
back_office_admin_user:
    path:     /users
    defaults: { _controller: BackOfficeBundle:User:admin}

back_office_admin_user_response:
    path:     /responseUser/{id}
    defaults: { _controller: BackOfficeBundle:User:response}

back_office_admin_user_delete:
    path:     /delete
    defaults: { _controller: BackOfficeBundle:User:delete}
