back_office_homepage:
    path:     /homepageBackOffice
    defaults: { _controller: BackOfficeBundle:Homepage:homepage }

# Routes gerant l'administration du blog:
    # Creation d'un article par l'administrateur:
back_office_article_new:
    path:     /new
    defaults: { _controller: BackOfficeBundle:Article:new}

    # Contrôle des articles par l'administrateur:
back_office_article_admin:
    path:     /adminArticle
    defaults: { _controller: BackOfficeBundle:Article:admin}

    # Validation des articles par l'administrateur:
back_office_article_response:
    path:     /response/{id}
    defaults: { _controller: BackOfficeBundle:Article:response}

    #Suppression des articles par l'administrateur:
back_office_article_delete:
    path:     /delete/{id}
    defaults: { _controller: BackOfficeBundle:Article:delete}

#  Routes gerant l'administration des terrains de sport :
back_office_ground_new:
    path:     /newGround
    defaults: { _controller: BackOfficeBundle:Ground:new}

# Routes gerant les users:
back_office_admin_user:
    path:     /users
    defaults: { _controller: BackOfficeBundle:User:admin}
