back_office_homepage:
    path:     /homepageBackOffice
    defaults: { _controller: BackOfficeBundle:Homepage:homepage }

# Routes gerant l'administration du blog:
    # Liste des articles:
back_office_article_list:
    path:     /list 
    defaults: { _controller: BackOfficeBundle:Article:list}

    # Statistiques multiples des articles:
back_office_article_articlesBySport:
    path:     /articlesBySport
    defaults: { _controller: BackOfficeBundle:Article:articlesBySport}
    
    # Creation d'un article par l'administrateur:
back_office_article_new:
    path:     /new
    defaults: { _controller: BackOfficeBundle:Article:new}

    # Contrôle des articles par l'administrateur:
back_office_article_admin:
    path:     /adminArticle
    defaults: { _controller: BackOfficeBundle:Article:admin}

    # Validation des articles par l'administrateur:
back_office_article_response:
    path:     /response/{id}
    defaults: { _controller: BackOfficeBundle:Article:response}
    requirements: 
        id: "[0-9]+"

    # Mise en statut Warned d'un article:
back_office_article_warnedArticle:
    path:     /warnedArticle/{id}
    defaults: { _controller: BackOfficeBundle:Article:warnedArticle}
    requirements: 
        id: "[0-9]+"

    # Mise à jour d'un article par l'administrateur:
back_office_article_update:
    path:     /update/{id}
    defaults: { _controller: BackOfficeBundle:Article:update}
    requirements: 
        id: "[0-9]+"

    # Affichage des articles mis en statut warned:
back_office_article_list_articles_warned:
    path:     /listArticlesWarned 
    defaults: { _controller: BackOfficeBundle:Article:listArticlesWarned}

    # Valmidation admin des articles mis en warned:
back_office_article_warned_response:
    path:     /responseWarnedArticle/{id}
    defaults: { _controller: BackOfficeBundle:Article:responseWarnedArticle}
    requirements: 
        id: "[0-9]+"

    # Suppression des articles par l'administrateur:
back_office_article_delete:
    path:     /delete/{id}
    defaults: { _controller: BackOfficeBundle:Article:delete}
    requirements: 
        id: "[0-9]+"

#  Routes gerant l'administration des commentaires:
    # Contrôle des comments par l'administrateur:
back_office_comment_admin:
    path:     /adminComment
    defaults: { _controller: BackOfficeBundle:Comment:admin}

    # Validation des comments par l'administrateur:
back_office_comment_response:
    path:     /responseComment/{id}
    defaults: { _controller: BackOfficeBundle:Comment:response}
    requirements: 
        id: "[0-9]+"

    # Suppression des comments par l'administrateur:
back_office_comment_delete:
    path:     /deleteComment/{id}
    defaults: { _controller: BackOfficeBundle:Comment:delete}
    requirements: 
        id: "[0-9]+"

#  Routes gerant l'administration des terrains de sport :
back_office_ground_list:
    path:     /listGround
    defaults: { _controller: BackOfficeBundle:Ground:list}

    # Creation d'un ground par l'administrateur:
back_office_ground_new:
    path:     /newGround
    defaults: { _controller: BackOfficeBundle:Ground:new}

    # Mise à jour d'un ground par l'administrateur:
back_office_ground_update:
    path:     /updateGround/{id}
    defaults: { _controller: BackOfficeBundle:Ground:update}
    requirements: 
        id: "[0-9]+"

    # Suppression des grounds par l'administrateur:
back_office_ground_delete:
    path:     /deleteGround/{id}
    defaults: { _controller: BackOfficeBundle:Ground:delete}
    requirements: 
        id: "[0-9]+"

    # Sélection des terrains non validés par l'admin:
back_office_ground_validAdmin:
    path:     /validAdminGround
    defaults: { _controller: BackOfficeBundle:Ground:validAdminGround}

    # Validation des terrains par admin:
back_office_ground_validationGround:
    path:      /validGround/{id}
    defaults: { _controller: BackOfficeBundle:Ground:validGround}
    requirements: 
        id: "[0-9]+"

    # Stats des terrains :
back_office_ground_stats:
    path:      /statsGrounds
    defaults:  { _controller: BackOfficeBundle:Ground:stats}

# Routes gerant les users:
    # Liste des users non valides par l'administrateur:
back_office_admin_user:
    path:     /users
    defaults: { _controller: BackOfficeBundle:User:admin}

    # Validation d'un user par l'administrateur:
back_office_admin_user_response:
    path:     /responseUser/{id}
    defaults: { _controller: BackOfficeBundle:User:response}
    requirements: 
        id: "[0-9]+"

    # Mise en table Warning d'un user:
back_office_admin_user_warned:
    path:     /warnedUser/{id}
    defaults: { _controller: BackOfficeBundle:User:warned}
    requirements: 
        id: "[0-9]+"

    # View des warnedUsers:
back_office_admin_warnedUsers:
    path:     /listWarned
    defaults: { _controller: BackOfficeBundle:User:warnedUsers}

    # Suppression d'un user par l'administrateur:
back_office_admin_user_delete:
    path:     /delete
    defaults: { _controller: BackOfficeBundle:User:delete}

    # Vue des stats Users:
back_office_admin_user_stats:
    path:     /statsUser
    defaults: { _controller: BackOfficeBundle:User:stats}

# Routes gerant les teams:
    # Controle des teams non validees:
back_office_list_team:
    path:     /listTeam 
    defaults: { _controller: BackOfficeBundle:Team:list} 

    # Validation d'une team par l'administrateur:
back_office_admin_team_response:
    path:     /responseTeam/{id}
    defaults: { _controller: BackOfficeBundle:Team:response}
    requirements: 
        id: "[0-9]+"

    # Suppression d'une team par l'administrateur:
back_office_team_delete:
    path:     /deleteTeam/{id}
    defaults: { _controller: BackOfficeBundle:Team:delete}
    requirements: 
        id: "[0-9]+"

    # Statistiques Teams:
back_office_team_getTeamsByInvitationsSent:
    path:     /getTeamsByInvitationsSent
    defaults: { _controller: BackOfficeBundle:Team:getTeamsByInvitationsSent}

# Routes gerant les messages :
back_office_message_list:
    path:     /listMessages 
    defaults: { _controller: BackOfficeBundle:Message:list}

    # Marquer les messages comme lus:
back_office_message_readMessage:
    path:     /readMessage/{id}
    defaults: { _controller: BackOfficeBundle:Message:readMessage}
    requirements: 
        id: "[0-9]+"

    #Lister les messages archives:
back_office_message_readMessage_list:
    path:     /listReadMessage
    defaults: { _controller: BackOfficeBundle:Message:listReadMessage}

    # Supprimer un message:
back_office_message_delete:
    path:     /deleteMessage/{id}
    defaults: { _controller: BackOfficeBundle:Message:delete}
    requirements: 
        id: "[0-9]+"

# Routes gerant les Sports :
back_office_sport_new:
    path:     /newSport
    defaults: { _controller: BackOfficeBundle:Sport:new}

back_office_sport_list:
    path:     /listSports
    defaults: { _controller: BackOfficeBundle:Sport:listSports}

# Routes gerant les invitations:
back_office_admin_invitations_stats:
    path:     /statsInvits
    defaults: { _controller: BackOfficeBundle:Invitation:stats}






























