<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticle()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT a 
			FROM FrontOfficeBundle:Article a 
			ORDER BY a.dateCreated DESC')
		->setMaxResults(1);

		return $query -> getSingleResult();
	}

	public function triArticle($category)
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT a 
			FROM FrontOfficeBundle:Article a 
			WHERE a.category LIKE :category')
		->setParameter('category',  $category);

		return $query ->getResult();
	}
}
