<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	# Selection des commentaires non validés par l'admin
	public function getUnvalidatedComment()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT c 
			FROM FrontOfficeBundle:Comment c 
			WHERE c.validationAdmin = false');

		return $query -> getResult();
	}

	# Comptage des comments postes 
	public function nbComments()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(c.id)
			FROM FrontOfficeBundle:Comment c');

		return $query -> getSingleScalarResult();
	}
}
