<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroundRepository extends EntityRepository
{
	public function validAdmin()
	{
		$query = $this ->getEntityManager()-> createQuery('
			SELECT g 
			FROM FrontOfficeBundle:Ground g 
			WHERE g.validAdmin = false
			ORDER BY g.dateCreated DESC');

		return $query -> getResult();
	}

	public function getGround()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT g 
			FROM FrontOfficeBundle:Ground g 
			ORDER BY g.dateCreated DESC')
		->setMaxResults(20);

		return $query -> getResult();
	}

	public function getGroundByRegion()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT g
			FROM FrontOfficeBundle:Ground g 
			WHERE g.validAdmin = true 
			GROUP BY g.region');
		
		return $this -> getResult();
	}

	public function getGroundByNbInvitations()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT g.name, COUNT(i.id) AS nb 
			FROM FrontOfficeBundle:Ground g 
			JOIN g.invitation i 
			WHERE i.accepted = true 
			AND i.denied = false
			GROUP BY g.name
			ORDER BY nb DESC')
		->setMaxResults(20);

		return $query -> getResult();
	}

	public function nbGrounds()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(g.id)
			FROM FrontOfficeBundle:Ground g
			WHERE g.validAdmin = true');

		return $query -> getSingleScalarResult();
	}

	public function getGroundsByNbUsers()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT g.name, COUNT(u.id) AS nb
			FROM FrontOfficeBundle:Ground g
			JOIN g.userGround u 
			WHERE u.validationAdmin = true 
			GROUP BY g.name
			ORDER BY nb DESC')
		->setMaxResults(25);

		return $query -> getResult();
	}

	public function getGroundsByNbTeams()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT g.name, COUNT(t.id) AS nb
			FROM FrontOfficeBundle:Ground g  
			JOIN g.team t
			WHERE t.validationAdmin = true
			GROUP BY g.name 
			ORDER BY nb DESC
			')
		->setMaxResults(25);

		return $query -> getResult();
	}
}
