<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroundRepository extends EntityRepository
{
	public function validAdmin()
	{
		$query = $this ->getEntityManager()-> createQuery('
			SELECT g 
			FROM FrontOfficeBundle:Ground g 
			WHERE g.validAdmin = false');

		return $query -> getResult();
	}

	public function getGround()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT g 
			FROM FrontOfficeBundle:Ground g 
			ORDER BY g.dateCreated DESC')
		->setMaxResults(20);

		return $query -> getResult();
	}

	public function getGroundByRegion()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT g
			FROM FrontOfficeBundle:Ground g 
			WHERE g.validAdmin = true 
			GROUP BY g.region');
		
		return $this -> getResult();
	}
}
