<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroundRepository extends EntityRepository
{
	public function validAdmin()
	{
		$query = $this ->getEntityManager()-> createQuery('
			SELECT g 
			FROM FrontOfficeBundle:Ground g 
			WHERE g.validAdmin = false');

		return $query -> getResult();
	}
}
