<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
	# Query sélectionnant les 50 dernières invitations:
	public function getInvitation()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT i 
			FROM FrontOfficeBundle:Invitation i 
			WHERE i.accepted = false
			ORDER BY i.dateCreated DESC')
		->setMaxResults(50);

		return $query -> getResult();
	}

	# Query permettant un tri des invitations par sport:
	public function sportInvitation($sport)
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT i 
			FROM FrontOfficeBundle:Invitation i 
			JOIN i.sport s
			WHERE i.accepted = false 
			AND s.name LIKE :sport')
		->setParameter('sport', $sport);

		return $query ->getResult();
	}

	# Query affichant les invitations acceptées par un user:
	public function seeInvitation($user)
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT i 
			FROM FrontOfficeBundle:Invitation i 
			JOIN i.user u
			WHERE i.accepted = true 
			AND u.username LIKE :user')
		->setParameter('user', $user);

		return $query -> getResult();
	}

	public function nbInvitations()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT COUNT(i.id) 
			FROM FrontOfficeBundle:Invitation i');

		return $query -> getSingleScalarResult();
	}

	public function nbInvitationsAccepted()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT COUNT(i.id) 
			FROM FrontOfficeBundle:Invitation i
			WHERE i.accepted = true');

		return $query -> getSingleScalarResult();
	}

	public function nbInvitationsDenied()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT COUNT(i.id) 
			FROM FrontOfficeBundle:Invitation i
			WHERE i.accepted = false');

		return $query -> getSingleScalarResult();
	}

	public function triInvitationByDestination($userTo)
	{
		$query = $this ->getEntityManager()->createQuery('
			SELECT i 
			FROM FrontOfficeBundle:Invitation i
			WHERE i.userTo LIKE :userTo
			AND i.accepted = false')
		->setParameter('userTo', $userTo);

		return $query -> getResult();
	}
}
