<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends EntityRepository
{
	public function nbMatches()		
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT COUNT(m.id)
			FROM FrontOfficeBundle:Matche m');

		return $query -> getSingleScalarResult();
	}

	public function getFuturesMatchesByTournament($id, $user)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Matche m 
			JOIN m.organizer u
			JOIN m.tournament t 
			WHERE t.id  LIKE :id
			AND u.id LIKE :user
			AND m.playedFuture = true')
		->setParameter('id', $id)
		->setParameter('user', $user);

		return $query -> getResult();
	}
}
