<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends EntityRepository
{
	public function nbMatches()		
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT COUNT(m.id)
			FROM FrontOfficeBundle:Matche m');

		return $query -> getSingleScalarResult();
	}

	public function getFuturesMatchesByTournament($id)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Matche m 			
			JOIN m.tournament t 
			WHERE t.id  LIKE :id			
			AND m.playedFuture = true')
		->setParameter('id', $id);		

		return $query -> getResult();
	}

	public function getPlayedMatchesByTournament($id)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Matche m 			
			JOIN m.tournament t 
			WHERE t.id  LIKE :id			
			AND m.played = true')
		->setParameter('id', $id);		

		return $query -> getResult();
	}
}
