<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends EntityRepository
{
	public function nbMatches()		
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT COUNT(m.id)
			FROM FrontOfficeBundle:Matche m');

		return $query -> getSingleScalarResult();
	}
}
