<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function getMessage()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Message m 
			ORDER BY m.dateCreated DESC');

		return $query -> getResult();
	}
}
