<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function getMessage()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Message m 
			WHERE m.readMessage = false
			ORDER BY m.dateCreated DESC');

		return $query -> getResult();
	}

	public function getMessageByAuthor()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT m.author, COUNT(m.id) as nb 
			FROM FrontOfficeBundle:Message m 
			ORDER BY m.dateCreated DESC
			GROUP BY nb DESC');

		return $query -> getResult();
	}

	public function nbMessages()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(m.id)
			FROM FrontOfficeBundle:Message m');

		return $query -> getSingleScalarResult();
	}

	public function getReadMessage()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT m 
			FROM FrontOfficeBundle:Message m 
			WHERE m.readMessage = true
			ORDER BY m.dateCreated DESC');

		return $query -> getResult();
	}

}
