<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
	public function getSportsByInvitsNumber()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT s.name, COUNT(i.id) as nb
			FROM FrontOfficeBundle:Sport s
			JOIN s.invitations i
			GROUP BY i.id
			');

		return $query -> getResult();
	}

}