<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{	
	#Query selectionnant les team non valides par l'admin:
	public function getTeamUnvalidated()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT t 
			FROM FrontOfficeBundle:Team t 
			WHERE t.validationAdmin = false');

		return $query -> getResult();
	}
}
