<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends EntityRepository
{
	public function getTournaments()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT t 
			FROM FrontOfficeBundle:Tournament t
			WHERE t.played = false 
			ORDER BY t.dateCreated DESC')
		->setMaxResults(8);

		return $query -> getResult();		
	}
}
